# For more information: https://laravel.com/docs/sail
version: '3'
services:
  mysql:
    container_name: food-db
    image: 'mysql:8.0.30'
    expose:
      - 3306
    # ports:
    #   - 3306:3306
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'food-mysql:/var/lib/mysql'
  api:
    container_name: food-api
    image: 'node:slim'
    ports:
      - 3000:3000
    environment:
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - ./api:/home/api
    working_dir: /home/api
    command: "npm start"

volumes:
  food-mysql:
    driver: local
